#!/bin/bash
sudo add-apt-repository ppa:ubuntu-wine/ppa
sudo apt-add-repository -y "deb http://repository.spotify.com stable non-free"
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 94558F59
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
sudo add-apt-repository ppa:team-xbmc/ppa
sudo apt-get update	
wget https://downloads.plex.tv/plex-media-server/0.9.12.1.1079-b655370/plexmediaserver_0.9.12.1.1079-b655370_amd64.deb
sudo dpkg -i plex*
wget http://download.virtualbox.org/virtualbox/4.3.26/virtualbox-4.3_4.3.26-98988~Ubuntu~raring_amd64.deb
sudo dpkg -i virtualbox*
wget https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.02.12_amd64.deb
sudo dkpg -i dropbox*
sudo apt-get update
sudo apt-get install build-essential ubuntu-restricted-extras gparted spotify-client ffmpeg wine1.7 google-chrome-beta qbittorrent curl software-properties-common kodi gparted openssh-server openssh-client sshfs synaptic python gimp samba openjdk-7-jdk openjdk-7-jre mysql-server git lamp-server^


